<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');

/**
 * Contao 
 * English translation file 
 * 
 * copyright  	Tim Gatzky 2012 
 * author     	Tim Gatzky <info@tim-gatzky.de>
 * package		catalognotelist_cataloglist
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MSC']['CATALOGNOTELIST_CATALOGLIST']['label_amount'] = 'Count: ';
$GLOBALS['TL_LANG']['MSC']['CATALOGNOTELIST_CATALOGLIST']['label_total'] = 'Sum all:';
$GLOBALS['TL_LANG']['MSC']['CATALOGNOTELIST_CATALOGLIST']['label_catalogs'] = 'Catalogs:';
$GLOBALS['TL_LANG']['MSC']['CATALOGNOTELIST_CATALOGLIST']['label_entries'] = 'In notelist:';
$GLOBALS['TL_LANG']['MSC']['CATALOGNOTELIST_CATALOGLIST']['input_amount'] = 'Amount';
$GLOBALS['TL_LANG']['MSC']['CATALOGNOTELIST_CATALOGLIST']['submit_update'] = 'Update';
$GLOBALS['TL_LANG']['MSC']['CATALOGNOTELIST_CATALOGLIST']['submit_remove'] = 'Remove';
$GLOBALS['TL_LANG']['MSC']['CATALOGNOTELIST_CATALOGLIST']['empty'] = 'Your notelist is empty.';


?>
