<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');

/**
 * Contao 
 * English translation file 
 * 
 * copyright  	Tim Gatzky 2012 
 * author     	Tim Gatzky <info@tim-gatzky.de>
 * package		catalognotelist_cataloglist
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['FMD']['cataloglist_notelist'] = array('Cataloglist (notelist)', '');

/**
 * Wildcard
 */
$GLOBALS['TL_LANG']['CATALOGLIST_NOTELIST']['WILDCARD'] =  "### CATALOG-LIST (NOTELIST) ###";

?>