<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');

/**
 * Contao extension: catalog 2.0.0 beta1 
 * English translation file 
 * 
 * copyright  Tim Gatzky 2012 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


$GLOBALS['TL_LANG']['tl_module']['catalognotelist_catalogs'] = array('Catalogs', 'Please choose the catalogs to use.'); 


?>